<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>omorobot</name>
  <version>0.0.0</version>
  <description>Meta package for omorobot</description>
  <maintainer email="t.shaped.person@gmail.com">Dr.K</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>omorobot_bringup</exec_depend>
  <exec_depend>omorobot_cartographer</exec_depend>
  <exec_depend>omorobot_description</exec_depend>
  <exec_depend>omorobot_navigation2</exec_depend>
  <exec_depend>omorobot_robot</exec_depend>
  <exec_depend>omorobot_teleop</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
